Taplytics Integration
mparticle-integrations/mparticle-apple-integration-example pull request #14
Opened 2018-08-21 20:38 UTC by jsalaber

2018-09-14 18:23 UTC, peterjenkins requested changes
Overall looks good, left a few inline comments.

2018-09-14 18:23 UTC, peterjenkins commented on mParticle-Taplytics.podspec
>                         This is the CompanyName integration for mParticle.
This line should be updated to match the summary.

2018-09-14 18:23 UTC, peterjenkins commented on mParticle-Taplytics.podspec
> +    s.ios.dependency 'Taplytics'
Can you please update this to be `~> 2.0`

2018-09-14 18:23 UTC, peterjenkins commented on mParticle-Taplytics/MPKitTaplytics.m
> +        NSString * apiKey = _configuration[API_KEY];
This can be updated to `self->_configuration` to prevent the compiler warning.

2018-09-14 18:23 UTC, peterjenkins commented on mParticle-Taplytics/MPKitTaplytics.m
> +        _started = YES;
Similarly to avoid warning this can be changed to `self->_started`

2018-09-17 14:51 UTC, jsalaber commented on mParticle-Taplytics.podspec
> +    s.ios.dependency 'Taplytics'
I've clamped the version so that it uses at least our most recent release 2.31.0

2018-09-17 14:58 UTC, jsalaber commented
@peterjenkins I've resolved your comments, let me know if there's anything else

2018-09-17 19:18 UTC, peterjenkins requested changes
Thanks for the updates, left one more inline feedback.

2018-09-17 19:18 UTC, peterjenkins commented on mParticle-Taplytics.podspec
> +    s.ios.dependency 'Taplytics', '>= 2.31.0'
To provide better context for my earlier feedback... we need to specifically lock the major version in all our kits to ensure reproducible builds for customers. Can you please update to use the `~>` operator with at least two version components e.g. `~> 2.31` or `~> 2.31.0` The former syntax will allow the minor and the patch to update vs. the latter also binds to the current minor version.

2018-09-18 15:04 UTC, jsalaber commented
@peterjenkins I've changed version dependency, it should be good now

2018-11-13 01:04 UTC, samdozor commented
This was released here: https://github.com/mparticle-integrations/mparticle-apple-integration-taplytics - closing!

2018-11-13 01:04 UTC, closed without merging