FollowAnalytics Integration
mparticle-integrations/mparticle-apple-integration-example pull request #17
Opened 2018-11-02 09:58 UTC by jjoaquim

2018-11-16 16:22 UTC, peterjenkins requested changes
Thanks for the PR. Left some inline feedback.

2018-11-16 16:22 UTC, peterjenkins commented on README.md
> +[Example integration](https://docs.mparticle.com/integrations/FollowAnalytics/event/)
Hyperlink user facing text needs update here.

2018-11-16 16:22 UTC, peterjenkins commented on mParticle-FollowAnalytics.podspec
> +    s.ios.dependency 'FollowAnalytics', '~> 6.0.0'
If you'd like, you can remove the last `.0` to allow minor version updates to be pulled in.

2018-11-16 16:22 UTC, peterjenkins commented on mParticle-FollowAnalytics.podspec
> +    s.ios.dependency 'mParticle-Apple-SDK', '~> 7'
Can you please re-add the minor version digit here? Otherwise if we release a new core major version, kits will get it immediately. (CocoaPods syntax here is a bit confusing.)

2018-11-16 16:22 UTC, peterjenkins commented on mParticle-FollowAnalytics/MPKitFollowAnalytics.m
> +        NSLog(@"You must initialize the FollowAnalytics SDK before starting mParticle. Please refer to https://dev.followanalytics.com/sdks/ios/documentation.");
This error message doesn't make any sense. Can you change it to say something like "the follow analytics SDK was not detected"

2018-11-16 16:22 UTC, peterjenkins commented on mParticle-FollowAnalytics/MPKitFollowAnalytics.m
> +- (MPKitExecStatus *)logScreen:(MPEvent *)event {
You don't need to implement methods if you don't have any functionality to execute in them, we will check responds to selector before calling.

2018-11-16 16:22 UTC, peterjenkins commented on mParticle-FollowAnalytics/MPKitFollowAnalytics.m
> +     [FollowAnalytics setOptInAnalytics:optOut];
I believe this should be `[FollowAnalytics setOptInAnalytics:!optOut];`.

2018-11-16 16:22 UTC, peterjenkins commented on mParticle_FollowAnalyticsTests/mParticle_FollowAnalyticsTests.m
> +    XCTAssertEqualObjects([MPKitFollowAnalytics kitCode], @123);
This should be updated to 132.

2019-03-26 20:26 UTC, jjoaquim commented
Hello @peterjenkins. I've pushed the changes you'd requested. Something wrong?

2019-03-26 20:27 UTC, peterjenkins commented
@jjoaquim Sorry this was closed by mistake, re-opening.

2019-03-26 20:30 UTC, jjoaquim commented
You're killing here. :)

2021-02-24 11:15 UTC, jjoaquim commented
Hello @peterjenkins,
Closing this one, to avoid the same treatment [this Android PR](https://github.com/mparticle-integrations/mparticle-android-integration-example/pull/11) got.

2021-02-24 11:15 UTC, closed without merging