Responsys Kit Implementation
mparticle-integrations/mparticle-apple-integration-example pull request #18
Opened 2018-11-02 14:14 UTC by s-wasan

This pull request contains:

    Kit implementation.
    Example(Separate) working with PushIOManager.
    PushIOManager framework, even though I would have liked example to integrate it separately.
    Unchanged mParticle-Responsys as CI fails if changes are made

**NOTE: I have made separate Example folder because mParticle-Example keeps giving error for CI**

2018-11-02 15:55 UTC, s-wasan commented
@peterjenkins  Travis is trying to run `mParticle-Example.xcodeproj`. It might need to find the right project and scheme to build.

2018-11-02 16:33 UTC, peterjenkins commented
@s-wasan I noticed that too... I will need to write up some more extensive instructions for the future to ensure people know to exactly which places to modify / rename including the travis.yml file as you have done.

Hopefully your scheme rename in xcodebuild command fixes things..

2018-11-02 16:52 UTC, s-wasan commented
@peterjenkins  yeah, I updated the travis file. Hopefully test will pass this time.

2018-11-02 18:17 UTC, peterjenkins commented
@s-wasan Thanks for continuing to try to troubleshoot this. I think I figured out why the carthage build command is failing.. you removed the example project but there's still a Podfile so travis automatically runs `pod install`.

If you remove the Podfile from the repo that should hopefully help. Also the last line in the .travis.yml needs an update to use an underscore in the test scheme name.

2018-11-02 18:34 UTC, s-wasan commented
@peterjenkins  Thanks for help. Removed the podfile. Test Scheme in this project does not contain the underscore. Tried locally the command was running good. 

Example project was messing with the build. Hopefully removing pod will run the tests.

2018-11-02 18:45 UTC, s-wasan commented
@peterjenkins  Finally passed. Please let me know if any other changes required. Thanks for bearing with me.

2018-11-02 20:47 UTC, samdozor requested changes
One issue I see with this is that it still requires customers to log events with a Responsys-specific event name such as `ResponsysEngagementTypePremium`. This won't be workable for our customers who have very specific naming taxonomies that they follow. 

I think the best way to do this is:
- Remove the `ENGAGEMENT_METRIC_*` constants and any processing of them in logEvent
- Add a `CUSTOM_FLAG_ENGAGEMENT_METRIC` constant
- Whenever an event is received with in logEvent or logCommerceEvent, see if it contains a `CUSTOM_FLAG_ENGAGEMENT_METRIC` custom flag, and call `trackEngagementMetric` with the value.
- You can likely keep the call to `trackEngagementMetric` for purchases (although do you mean to be calling it for EACH product?) you have today in `logCommerceEvent`, but account for if the custom flag is present as well.

2018-11-05 17:01 UTC, codestergit commented
@samdozor Updated the pull request. Please review.

2018-11-05 17:02 UTC, s-wasan commented
@samdozor Updated the pull request. Please review.

2018-11-05 20:55 UTC, peterjenkins commented on mParticle-Responsys/MPKitResponsys.m
> +            [[self pushIOManager] registerForAllRemoteNotificationTypes:^(NSError *error, NSString *response) {
Can you please avoid registering for push notifications here? Our customers require having control over when / how the push registration prompt is displayed to the user.

2018-11-07 10:39 UTC, s-wasan commented
@peterjenkins @samdozor  Updated the pull request. It should be good now. 
Please review.

2018-11-13 01:05 UTC, samdozor commented
Thanks again for all of the work here! I've move the repo over to here, and removed the PushIO framework as well as the podspec: https://github.com/mparticle-integrations/mparticle-apple-integration-responsys

2018-11-13 01:05 UTC, closed without merging