Iterable mParticle integration for deeplinking
mparticle-integrations/mparticle-apple-integration-example pull request #9
Opened 2017-04-19 20:44 UTC by davidtruong

2017-05-01 22:28 UTC, samdozor requested changes

2017-05-01 22:28 UTC, samdozor commented on README.md
> +    [[MParticle sharedInstance] continueUserActivity:userActivity restorationHandler:restorationHandler];
this is called automatically by our SDK since we proxy the app delegate, so can be left out of docs.

2017-05-01 22:28 UTC, samdozor commented on mParticle-iterable/IterableMPHelper.h
> +#define ITBL_DEEPLINK_IDENTIFIER @"/a/[a-zA-Z0-9]+"
similar to Android - is this supposed to match a specific URL?

2017-05-01 22:28 UTC, samdozor commented on mParticle-iterable/MPKitIterable.m
> +    return @1003;
you can return MPKitInstanceIterable here

2017-05-01 22:28 UTC, samdozor commented on mParticle-iterable/MPKitIterable.m
> +    NSString *appKey = configuration[@"<dictionary key to retrieve API Key>"];
This line should be removed.

2017-05-01 22:28 UTC, samdozor commented on mParticle-iterable/MPKitIterable.m
> +- (id const)providerKitInstance {
This method should not be implemented if there's no instance to return.

2017-05-01 22:58 UTC, davidtruong commented on mParticle-iterable/MPKitIterable.m
> +    return @1003;
Should I be making MPKitInstanceIterable static (L22)? Or are you suggesting something else?

2017-05-01 23:00 UTC, davidtruong commented on mParticle-iterable/IterableMPHelper.h
> +#define ITBL_DEEPLINK_IDENTIFIER @"/a/[a-zA-Z0-9]+"
Yes we only track the deeplinks if the link matches the pattern containing '/a/'

2017-05-02 16:16 UTC, davidtruong commented on mParticle-iterable/MPKitIterable.m
> +    return @1003;
@samdozor: All the examples I see hardcode the return value. Let me know how I should change this.

2017-05-17 17:56 UTC, peterjenkins approved these changes
This has been released as 6.14.0.

2017-05-17 17:57 UTC, closed without merging